// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASmLuAJHzEsx35TiCqs9wsY_P5fLL4WPU',
    appId: '1:421083927001:web:50834423f0481ec41409c8',
    messagingSenderId: '421083927001',
    projectId: 'phoneauth-71cda',
    authDomain: 'phoneauth-71cda.firebaseapp.com',
    storageBucket: 'phoneauth-71cda.appspot.com',
    measurementId: 'G-FCZEJFR3FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsEH7Rspgt1DwVWVWrM4uJsYjik1p67_M',
    appId: '1:421083927001:android:5fe8a0b4723256e31409c8',
    messagingSenderId: '421083927001',
    projectId: 'phoneauth-71cda',
    storageBucket: 'phoneauth-71cda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPoHYVZQym6SGzZ1bDRab9YXL_KtweQE',
    appId: '1:421083927001:ios:40e34b37e86862dd1409c8',
    messagingSenderId: '421083927001',
    projectId: 'phoneauth-71cda',
    storageBucket: 'phoneauth-71cda.appspot.com',
    androidClientId: '421083927001-j1i9uglc446ila1jf5ov3mcr3kjn3kni.apps.googleusercontent.com',
    iosClientId: '421083927001-im37acqljufebe1bdtsr44grh13f0knb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHPoHYVZQym6SGzZ1bDRab9YXL_KtweQE',
    appId: '1:421083927001:ios:d3aee46e6842fb131409c8',
    messagingSenderId: '421083927001',
    projectId: 'phoneauth-71cda',
    storageBucket: 'phoneauth-71cda.appspot.com',
    androidClientId: '421083927001-j1i9uglc446ila1jf5ov3mcr3kjn3kni.apps.googleusercontent.com',
    iosClientId: '421083927001-qg64omdea9t7clhuqddn5gqsk9r0q4o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.testp.RunnerTests',
  );
}
